version: '1.0'

services:
 mongodb:
    image: mongo:latest
    container_name: my-mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all

volumes:
 mongodb_data: